export const curing = {
  eat: {
    id: "eat",
    fullName: "Eat",
    firstPerson: false,
    secondPerson: false,
    thirdPerson: /^(?<user>\w+) eats (?<target>.+)\.$/,
    profession: ["general"],
    skill: "",
    balance: "herb",
    multiLine: 0,
    tags: [],
    length: 1.6,
  },
  apply: {
    id: "apply",
    fullName: "Apply",
    firstPerson: false,
    secondPerson: false,
    thirdPerson:
      /^(?<user>\w+) takes some salve from a vial and rubs it on \w+ (?<target>.+)\.$/,
    profession: ["general"],
    skill: "",
    balance: "salve",
    multiLine: 0,
    tags: [],
    length: 1,
  },
  smoke: {
    id: "smoke",
    fullName: "Smoke",
    firstPerson: false,
    secondPerson: false,
    thirdPerson: /^(?<user>\w+) takes a long drag off \w+ (?<target>.+)\.$/,
    profession: ["general"],
    skill: "",
    balance: "smoke",
    multiLine: 0,
    tags: [],
    length: 1.6,
  },
  sip: {
    id: "sip",
    fullName: "Sip",
    firstPerson: false,
    secondPerson: false,
    thirdPerson: /^(?<user>\w+) takes a drink from (?:a|an) (?<target>.+)\.$/,
    profession: ["general"],
    skill: "",
    balance: "sip",
    multiLine: 0,
    tags: [],
    length: 1.6,
  },
  focus: {
    id: "focus",
    fullName: "Focus",
    firstPerson: false,
    secondPerson: false,
    thirdPerson: /^A look of extreme focus crosses the face of (?<user>\w+)\.$/,
    profession: ["general"],
    skill: "",
    balance: "focus",
    multiLine: 0,
    tags: [],
    length: 2.5,
  },
};

export default Object.values(curing);
