export const actions = [
    {
        id: "chasten",
        fullName: "Chasten",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^A dark bolt of energy erupts from the mace held by (?<user>\w+), afflicting (?<target>.+?) with a chastening magic\.$/,
        profession: ["priest"],
        skill: "spirituality",
        balance: "balance",
        multiLine: 0,
        tags: [],
        length: 2.9,
    },
    {
        id: "smite",
        fullName: "Smite",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^(?<user>\w+) utters a prayer and smites (?<target>.+?)'s (?<limb>.+?) with an Auroran Mace\.$/,
        profession: ["priest"],
        skill: "spirituality",
        balance: "equilibrium",
        multiLine: 0,
        tags: [],
        length: 2.8,
    },
    {
        id: "guilt",
        fullName: "Guilt",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^"And your guilt will be made plain," (?<user>\w+) proselytises, finger raised to point at (?<target>.+?)\.$/,
        profession: ["priest"],
        skill: "zeal",
        balance: "prayer",
        multiLine: 0,
        tags: ["aff"],
        affs: ["guilt"],
        length: 1.7,
    },
    {
        id: "guilt2",
        fullName: "Guilt",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^"Know the pain which you have caused," (?<user>\w+) proselytises, finger raised to point at (?<target>.+?)\.$/,
        profession: ["priest"],
        skill: "zeal",
        balance: "prayer",
        multiLine: 0,
        tags: ["aff"],
        affs: ["guilt"],
        length: 1.7,
    },
    {
        id: "purge",
        fullName: "Purge",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^"I deem you unfit for Creation!" (?<user>\w+) proclaims, pointing an imperious finger at (?<target>.+?)\.$/,
        profession: ["priest"],
        skill: "zeal",
        balance: "prayer",
        multiLine: 0, //A line of golden flame leaps forth, lashing about Amranu and searing him to the bone.
        tags: ["aff"],
        affs: ["ablaze"],
        length: 2.3,
    },
    {
        id: "penance",
        fullName: "Penance",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^"And face your penance!" denounces (?<user>\w+), hand raised in warding against (?<target>.+?)\.$/,
        profession: ["priest"],
        skill: "zeal",
        balance: "prayer",
        multiLine: 0, //A line of golden flame leaps forth, lashing about Amranu and searing him to the bone.
        tags: ["aff"],
        affs: ["paralysis"],
        length: 1.6,
    },
    {
        id: "light",
        fullName: "Light",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^"May the Light lead, and we never fail to follow!" cries out (?<user>\w+)\.$/,
        profession: ["priest"],
        skill: "zeal",
        balance: "prayer",
        multiLine: 0,
        tags: ["heal", "cure"],
        affs: [],
        length: 3.0,
    },
    {
        id: "inquisition",
        fullName: "Inquisition",
        firstPerson: false,
        secondPerson: false,
        thirdPerson: /^Pointing at \w+ with a single raised finger, (?<user>\w+) recites a list of (?<target>.+?)'s transgressions, condemning \w+ actions and words\. A blaze of holy fire surges about \w+ as he dictates \w+'s sentence\.$/,
        profession: ["priest"],
        skill: "devotion",
        balance: "equilibrium",
        multiLine: 0,
        tags: ["aff"],
        affs: ["inquisition"],
        length: 3.5,
    },
];