export const sylvan = [
  {
    id: "thornpierce",
    fullName: "Thornpierce",
    firstPerson:
      /^A thorny vine reaches out from you and pierces through (?<target>.+?)'s translucent shield, causing it to fade\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["sylvan"],
    skill: "attainment",
    balance: "free",
    multiLine: 0,
    info: "Raze",
    tags: ["pve", "raze"],
    length: 3,
  },
  {
    id: "torrent",
    fullName: "Torrent",
    firstPerson:
      /^(?<target>.+?) coughs and splutters as you channel a gout of water at \w+ face\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["sylvan"],
    skill: "attainment",
    balance: "free",
    multiLine: 0,
    tags: ["pve", "damage"],
    length: 0,
  },
  {
    id: "rockshot",
    fullName: "Rockshot",
    firstPerson:
      /^You form a small pebble, then channel air to fling it violently at (?<target>.+?)'s head, causing \w+ to look dazed\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["sylvan"],
    skill: "attainment",
    balance: "free",
    multiLine: 0,
    info: "Amensia",
    tags: ["pve", "aff"],
    affs: ["amensia"],
    length: 0,
  },
  {
    id: "stonevine",
    fullName: "Stonevine",
    firstPerson:
      /^You summon a great vine to wrap itself around (?<target>.+?), then channel the element of earth into it, causing it to become rock hard and shatter as it constricts around \w+\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["sylvan"],
    skill: "attainment",
    balance: "free",
    multiLine: 0,
    info: false,
    tags: ["pve", "damage"],
    affs: [],
    length: 0,
  },
  {
    id: "leechroot",
    fullName: "Leechroot",
    firstPerson:
      /^A deadly root flies from your hand and burrows into (?<target>.+?)'s flesh, but is unable to find sufficient sustenance\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["sylvan"],
    skill: "attainment",
    balance: "free",
    multiLine: 0,
    info: false,
    tags: ["pve", "damage"],
    affs: [],
    length: 0,
  },
];
