export const actions = [
  {
    id: "limerick",
    fullName: "Limerick",
    firstPerson: false,
    secondPerson:
      /^\w+ eyes gleaming, (?<user>\w+) smiles and quickly sings a jaunty limerick at you\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    tags: ["aff"],
    affs: ["impatience"],
    length: 0,
  },
  {
    id: "ode",
    fullName: "Ode",
    firstPerson: false,
    secondPerson:
      /^With a wink, (?<user>\w+) recites "Ode to Elixirs" to you\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    tags: ["aff"],
    affs: ["addiction"],
    length: 0,
  },
  {
    id: "epic",
    fullName: "Epic",
    firstPerson: false,
    secondPerson:
      /^You are held motionless by (?<user>\w+)'s epic tale of Nicator's heroism and bravery\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    tags: ["aff"],
    affs: ["paralysis"],
    length: 0,
  },
  {
    id: "maqam",
    fullName: "Maqam",
    firstPerson: false,
    secondPerson:
      /^You feel suddenly clumsy beside the graceful maqam of el'Jazira that (?<user>\w+) sings at you\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    tags: ["aff"],
    affs: ["clumsiness"],
    length: 0,
  },
  {
    id: "birdDitty",
    fullName: "Ditty",
    firstPerson: false,
    secondPerson:
      /^The songbird upon (?<user>\w+)'s shoulder twitters an irritating ditty at you, disrupting your mind\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    info: "Songbird",
    tags: ["aff"],
    affs: ["addiction"],
    length: 0,
  },
  {
    id: "birdRequiem",
    fullName: "Requiem",
    firstPerson: false,
    secondPerson:
      /^The songbird upon (?<user>\w+)'s shoulder launches into a requiem for historical Seleucar so convincing that paranoia of the future sets in\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    info: "Songbird",
    tags: ["aff"],
    affs: ["paranoia"],
    length: 0,
  },
  {
    id: "birdPassion",
    fullName: "Passion",
    firstPerson: false,
    secondPerson:
      /^The songbird upon (?<user>\w+)'s shoulder sings a grave, perfect mimicry of the Passion of Imithia to you\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    info: "Songbird",
    tags: ["aff"],
    affs: ["stupidity"],
    length: 0,
  },
  {
    id: "birdPastorale",
    fullName: "Pastorale",
    firstPerson: false,
    secondPerson:
      /^The songbird upon (?<user>\w+)'s shoulder sings a pastorale of the fields and streams to you\. You feel reluctant to leave the ground\.$/,
    thirdPerson: false,
    profession: ["bard"],
    skill: "harmonics",
    balance: "free",
    multiLine: 0,
    info: "Songbird",
    tags: ["aff"],
    affs: ["vertigo"],
    length: 0,
  },
];
