export const dragon = [
  //#region Attainment
  {
    id: "glaciate",
    fullName: "Glaciate",
    firstPerson:
      /^You breathe a column of icy air at (?<target>.+?)'s head, stunning \w+\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["blue dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Stun",
    tags: ["pve", "stun"],
    length: 3.0,
  },
  {
    id: "frostrive",
    fullName: "Frostrive",
    firstPerson:
      /^(?<target>.+?)'s translucent shield cracks and fades away as you breathe an icy blast at it\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["blue dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Raze",
    tags: ["pve", "raze"],
    length: 3.0,
  },
  {
    id: "override",
    fullName: "Override",
    firstPerson:
      /^You barrel into (?<target>.+?) and knock \w+ to the ground before stomping over \w+ prone form\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["blue dragon", "black dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "ague",
    fullName: "Ague",
    firstPerson:
      /^You let loose a steady stream of cold air around (?<target>.+?), who begins to shiver uncontrollably\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["blue dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Clumsy",
    tags: ["pve", "clumsy"],
    length: 3.0,
  },
  {
    id: "dragonchill",
    fullName: "Dragonchill",
    firstPerson:
      /^You form small chunks of ice in your enormous maw, then spit them at (?<target>.+?) in a barrage\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["blue dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "frostwave",
    fullName: "Frostwave",
    firstPerson: /^You breathe a wave of icy air at (?<target>.+?)\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["blue dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "dragonsting",
    fullName: "Dragonsting",
    firstPerson:
      /^You swing your mighty tail around, stabbing (?<target>.+?) with an acid-covered spine\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["black dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Sensitivity",
    tags: ["pve", "damage", "sensitivity"],
    length: 3.0,
  },
  {
    id: "dragonspit",
    fullName: "Dragonspit",
    firstPerson:
      /^You spit a stream of acidic venom at (?<target>.+?) who writhes in agony as the spittle seeps into \w+ skin\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["black dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "dragonspitTick",
    fullName: "Dragonspit Tick",
    firstPerson: false,
    secondPerson: false,
    thirdPerson:
      /^(?<target>.+?) writhes in agony as acidic spittle eats away at \w+ skin\.$/,
    profession: ["black dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "corrode",
    fullName: "Corrode",
    firstPerson:
      /^You open your gigantic maw and spew acid on (?<target>.+?)\. \w+ dodges to the side and is only partially covered by the corrosive slime\.$/,
    secondPerson: false,
    thirdPerson:
      /^(?<user>\w+) opens \w+ gigantic maw and spews acid on (?<target>.+?)\. \w+ is too clumsy to dodge and is covered in the corrosive slime\.$/,
    profession: ["black dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "dragonfear",
    fullName: "Dragonfear",
    firstPerson:
      /^You open your enormous maw and let loose a mighty roar at (?<target>.+?), causing \w+ to quail in fear\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["black dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Fear",
    tags: ["pve", "damage", "fear"],
    length: 3.0,
  },
  {
    id: "dragonblaze",
    fullName: "Dragonblaze",
    firstPerson:
      /^You breathe a long torrent of flame at (?<target>.+?), igniting \w+ skin\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "dragonblazeTick",
    fullName: "Dragonblaze tick",
    firstPerson: false,
    secondPerson: false,
    thirdPerson:
      /^(?<target>.+?) is wracked with pain as the flames of dragonbreath wreathe over \w+ skin\.$/,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "scorch",
    fullName: "Scorch",
    firstPerson:
      /^You blacken (?<target>.+?)'s flesh with a quick blast of flame, slowing \w+ healing process\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Inhibit",
    tags: ["pve", "inhibit"],
    length: 3.0,
  },
  {
    id: "overwhelm",
    fullName: "Overwhelm",
    firstPerson:
      /^You charge quickly at (?<target>.+?), throwing your mighty form into \w+ and sending \w+ staggering back\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "dragontaunt",
    fullName: "Dragontaunt",
    firstPerson:
      /^You slap your tail on the ground while growling at (?<target>.+?), forcing \w+ to recklessly attack\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Recklessness",
    tags: ["pve", "recklessness"],
    length: 3.0,
  },
  {
    id: "flamebath",
    fullName: "Flamebath",
    firstPerson:
      /^You blast (?<target>.+?) with a bath of flame, but \w+ is able to avoid the brunt of the blast\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: false,
    tags: ["pve", "damage"],
    length: 3.0,
  },
  {
    id: "melt",
    fullName: "Melt",
    firstPerson:
      /^You breathe a white-hot blast of flame at (?<target>.+?) and burn away \w+ translucent shield\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["red dragon"],
    skill: "attainment",
    balance: "battlerage",
    info: "Raze",
    tags: ["pve", "raze"],
    length: 3.0,
  },
  //#endregion
];
