export const magi = {
  squeeze: {
    id: "squeeze",
    fullName: "Squeeze",
    firstPerson:
      /^You raise a clenched fist and in obedience the earth rises in turn, a great hand of stone unfurling to clamp about (?<target>.+?) in a vice-like squeeze\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "damage"],
    length: 16.0,
  },
  windlash: {
    id: "windlash",
    fullName: "Windlash",
    firstPerson:
      /^You draw upon the power of air to summon sharp gusts of wind which begin to whip across (?<target>.+?)'s exposed flesh\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "damage"],
    length: 16.0,
  },
  windlashTick: {
    id: "windlashTick",
    fullName: "Windlash Tick",
    firstPerson:
      /^Sharp gusts of wind whip across (?<target>.+?)'s exposed flesh\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "damage"],
    length: 16.0,
  },
  firefall: {
    id: "firefall",
    fullName: "Firefall",
    firstPerson:
      /^You raise your hands dramatically and summon a mighty flaming rock from the sky down at (?<target>.+?), but \w+ dodges aside and is only dealt a glancing blow\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "damage"],
    info: "non-combo",
    length: 16.0,
  },
  dilation: {
    id: "dilation",
    fullName: "Dilation",
    firstPerson:
      /^You summon a polar vortex in a tight field around (?<target>.+?), chilling the small pocket so intensely that time itself begins to slow\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "damage"],
    length: 16.0,
  },
  stormbolt: {
    id: "stormbolt",
    fullName: "Stormbolt",
    firstPerson:
      /^A bolt of lightning roars out from your hands as you cast a powerful spell at (?<target>.+?), inciting sensitive nerves across \w+ skin\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "damage"],
    length: 16.0,
  },
  disintegrate: {
    id: "disintegrate",
    fullName: "Disintegrate",
    firstPerson:
      /^You summon a whirlwind of flame around (?<target>.+?) which consumes \w+ translucent shield\.$/,
    secondPerson: false,
    thirdPerson: false,
    profession: ["magi"],
    skill: "attainment",
    balance: "battlerage",
    tags: ["pve", "raze"],
    info: "raze",
    length: 16.0,
  },
};

export default Object.values(magi);
