// The ordering in these arrays is matching precedence. Keep it explicit rather
// than deriving it from module export enumeration.

// Attainment
import {
  bard,
  depthswalker,
  dragon,
  magi,
  occultist,
  psion,
  runewarden,
  sylvan,
  unnamable,
} from "./skills/attainment";

// Skills
import {
  aeonics,
  artificing,
  bladedance,
  composition,
  crystalism,
  curses,
  devotion,
  domination,
  dragoncraft,
  elementalism,
  emulation,
  evileye,
  ignition,
  knights,
  memorium,
  occultism,
  oppression,
  pranks,
  propagation,
  psionics,
  shadowmancy,
  spirituality,
  subterfuge,
  tarot,
  tekura,
  venom,
  weaponmastery,
  weatherweaving,
  weaving,
  zeal,
} from "./skills";

// General
import { curing, gear, general, talismans, tattoos } from "./general";

// NPCs
import {
  ageiro,
  barrow,
  battlesite,
  crust,
  dustsongSpire,
  elementalEmbassy,
  emberveil,
  grukaiSwamp,
  istarion,
  judgementMountain,
  lupineHuntingGrounds,
  mannamot,
  nur,
  riagath,
  tapoa,
  tirMurann,
  tuar,
  underworld,
  yggdrasil,
} from "./areas";

export const actionDefinitions = [
  ...bard,
  ...depthswalker,
  ...dragon,
  ...magi,
  ...occultist,
  ...psion,
  ...runewarden,
  ...sylvan,
  ...unnamable,
  ...aeonics,
  ...artificing,
  ...bladedance,
  ...composition,
  ...crystalism,
  ...curses,
  ...devotion,
  ...domination,
  ...dragoncraft,
  ...elementalism,
  ...emulation,
  ...evileye,
  ...ignition,
  ...knights,
  ...memorium,
  ...occultism,
  ...oppression,
  ...pranks,
  ...propagation,
  ...psionics,
  ...shadowmancy,
  ...spirituality,
  ...subterfuge,
  ...tarot,
  ...tekura,
  ...venom,
  ...weaponmastery,
  ...weatherweaving,
  ...weaving,
  ...zeal,
  ...curing,
  ...gear,
  ...general,
  ...talismans,
  ...tattoos,
];

export const npcDefinitions = [
  ...ageiro,
  ...barrow,
  ...battlesite,
  ...crust,
  ...dustsongSpire,
  ...elementalEmbassy,
  ...emberveil,
  ...grukaiSwamp,
  ...istarion,
  ...judgementMountain,
  ...lupineHuntingGrounds,
  ...mannamot,
  ...nur,
  ...riagath,
  ...tapoa,
  ...tirMurann,
  ...tuar,
  ...underworld,
  ...yggdrasil,
];
