export const npcs = [
  {
    user: "a rajamala slaver",
    areaId: [337],
    areaName: "the fathomless expanse of the World Tree",
    firstPerson:
      /^Moving with astonishing speed, a rajamala slaver unleashes the power of his feline claws against your skin\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "loki"],
    length: 4.0,
  },
  {
    user: "a rajamala slaver",
    areaId: [337],
    areaName: "the fathomless expanse of the World Tree",
    firstPerson:
      /^A rajamala slaver uses his massive bulk to slam your body to the ground\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "brokenleftleg", "brokenrightleg", "prone"],
    length: 4.0,
  },
  {
    user: "a rajamala slaver",
    areaId: [337],
    areaName: "the fathomless expanse of the World Tree",
    firstPerson:
      /^A rajamala slaver leaps into the air and hurtles towards you\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "brokenleftleg", "brokenrightleg", "prone"],
    length: 4.0,
  },
  {
    user: "a huge rat",
    areaId: [338],
    areaName: "the fathomless expanse of the World Tree",
    firstPerson:
      /^A huge rat snarls in fury as he bites down on your arm, sending a series of spasms racing through your body\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "loki", "loki"],
    length: 4.0,
  },
  {
    user: "a huge rat",
    areaId: [338],
    areaName: "the fathomless expanse of the World Tree",
    firstPerson:
      /^Hissing with rage, a huge rat swipes a claw across your knees\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "loki"],
    length: 4.0,
  },
  {
    user: "a huge rat",
    areaId: [338],
    areaName: "the fathomless expanse of the World Tree",
    firstPerson:
      /^Snarling as he leaps at your legs, a huge rat rips and tears into your flesh, his mouth filling with blood and saliva\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "loki", "torntendons", "clumsiness"],
    length: 4.0,
  },

  {
    user: "an angel spearbearer",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^In a trained motion, an angel spearbearer drives the pointy end of his spear into both of your shoulders with two well-placed jabs\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an angel spearbearer",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^With force and precision, an angel spearbearer drives his spear into your torso, impaling you frightfully\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "web"],
    length: 2,
  },
  {
    user: "an angel spearbearer",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^Flipping his spear around in a trained motion, an angel spearbearer hits you on the side of the head with the weapon's blunt end\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "stun"],
    length: 2,
  },
  {
    user: "an angel spearbearer",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^Wielding his spear in one hand and lifting it above his head, an angel spearbearer chants ancient words before throwing the sizzling spear at you as coruscating energy crackles along the weapon's surface\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "stun"],
    length: 2,
  },
  {
    user: "an angel spearbearer",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^Spinning his spear in one hand, an angel spearbearer ducks down low and jabs his spear between your legs before twisting it, causing you to fall to the ground\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "prone", "brokenleftleg"],
    length: 2,
  },
  {
    user: "an angel spearbearer",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^A look of sheer determination clear on his face, an angel spearbearer sweeps his spear in a wide arc with practiced control\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "prone"],
    length: 2,
  },
  {
    user: "a vanguard angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^A vanguard angel points his radiant sword directly at you, a bolt of pure energy bursting forth and slamming into your chest\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a vanguard angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^A vanguard angel whirls his fiery sword in a controlled arc that slices you from shoulder to sternum\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a vanguard angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^His luminous sword a blur of fiery strikes, a vanguard angel stabs you repeatedly, causing notable damage with each thrust\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a vanguard angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^With a snap, the angel's ethereal wings solidify into twin appendages of finely honed death\. He deploys them with a graceful pivot, mercilessly slicing all in their path\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an expulsor angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^An expulsor angel slams her buckler into your sternum with brutal force\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an expulsor angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^A single beat of her wings carries an expulsor angel briefly aloft before she dives towards you in a silent blur, driving her javelin deep into the juncture of your neck and shoulder\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an expulsor angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^Batting away your defences, an expulsor angel drives her javelin deep into your exposed body\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an expulsor angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^An expulsor angel slams her buckler into your sternum with brutal force\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an inquisitor angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^An inquisitor angel raises her palm and sends a wave of energy to slam painfully into you\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "an inquisitor angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^Pivoting in a tight circle, an inquisitor angel transforms her wings into a fiery blaze that sweeps relentlessly through the room, engulfing you in flames\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "burning"],
    length: 2,
  },
  {
    user: "a watcher angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^A watcher angel turns his burning, sightless gaze in your direction, causing searing agony to erupt throughout your body\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a watcher angel",
    areaId: [401],
    areaName: "First Circle of Nur",
    firstPerson:
      /^A watcher angel turns his burning, sightless gaze in your direction, causing searing agony to erupt throughout your body\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a muscular angelic razer",
    areaId: [398],
    areaName: "Fifth Circle of Nur",
    firstPerson:
      /^Closing with you briskly, a muscular angelic razer punches out with his sheathed sword, winding you with a hefty blow to the stomach\. Stepping back unhurriedly, he pulls the sword from its scabbard and slashes at you twice in quick succession\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a muscular angelic razer",
    areaId: [398],
    areaName: "Fifth Circle of Nur",
    firstPerson:
      /^A muscular angelic razer's wings flare powerfully, sending him colliding into you with his shoulder\. The impact tosses you to the ground like a rag doll, and you can do naught but watch as his hands move in a blur, liberating from its sheath a bastard sword, and guiding it through the air to slice painfully into your exposed form\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "prone"],
    length: 2,
  },
  {
    user: "a lithe angelic razer",
    areaId: [398],
    areaName: "Fifth Circle of Nur",
    firstPerson:
      /^Taking a brisk step backwards, a lithe angelic razer glares piercingly at you with unseeing eyes, her movements filled with contempt\. Without warning, pain flares in your consciousness, radiating from your cranium to fill your body with rending agony\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "stupidity"],
    length: 2,
  },
  {
    user: "a lithe angelic razer",
    areaId: [398],
    areaName: "Fifth Circle of Nur",
    firstPerson:
      /^A lithe angelic razer abruptly blurs into motion, leaping through the air and slicing into you with her longswords\. An instant later, her full weight crashes into you as she plants one foot on your chest and kicks off, before floating to the ground a few paces away\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2,
  },
  {
    user: "a lithe angelic razer",
    areaId: [398],
    areaName: "Fifth Circle of Nur",
    firstPerson:
      /^Advancing upon you swiftly, a lithe angelic razer swings her left-hand longsword in a powerful overarm arc, inflicting a withering strike that crushes your bones\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "brokenleftarm"], //random ARM break
    length: 2,
  },
  {
    user: "a solemn angel",
    areaId: [397],
    areaName: "Sixth Circle of Nur",
    firstPerson:
      /^Looking down on you with primal ire, a solemn angel jerks her hand up, causing shafts of light to burst through the ground, impaling you in place\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "impale"],
    length: 2,
  },
  {
    user: "a solemn angel",
    areaId: [397],
    areaName: "Sixth Circle of Nur",
    firstPerson:
      /^Darting towards you with blinding speed, a solemn angel slashes her hand across your chest, leaving a ghastly glowing wound behind\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "burning"],
    length: 2,
  },
  {
    user: "a solemn angel",
    areaId: [397],
    areaName: "Sixth Circle of Nur",
    firstPerson:
      /^Drawing her wings out to full length, a solemn angel swiftly claps them together, buffeting you with a massive gust of wind\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "prone"],
    length: 2,
  },
  {
    user: "a Migri warrior",
    areaId: [257],
    areaName: "Judgement Mountain",
    firstPerson:
      /^A Migri warrior's eyes narrow as he grasps his longsword with both hands and raises it over his head before bringing it down across your chest\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2.5,
  },
  {
    user: "a Migri warrior",
    areaId: [257],
    areaName: "Judgement Mountain",
    firstPerson:
      /^In a skillful display of swordsmanship, a Migri warrior slashes diagonally across your body before striking you again with a jab through your belly\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2.5,
  },
  {
    user: "a Migri warrior",
    areaId: [257],
    areaName: "Judgement Mountain",
    firstPerson:
      /^A Migri warrior bares his teeth and lunges at you with his longsword, the blade easily sliding into your body\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2.5,
  },
  {
    user: "a Migri warrior",
    areaId: [257],
    areaName: "Judgement Mountain",
    firstPerson:
      /^A Migri warrior strikes you in the face with the hilt of his sword\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2.5,
  },
  {
    user: "Begath, the Migri mage",
    areaId: [257],
    areaName: "Judgement Mountain",
    firstPerson:
      /^Begath, the Migri mage blows gently over his fingertips, causing them to turn blue and frost over before reaching towards you and sending several ice spikes in your direction\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2.5,
  },
  {
    user: "a gigantic angler fish",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A gigantic angler fish rapidly lunges towards you, its razor-sharp teeth snapping shut on your arm\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 2.0,
  },
  {
    user: "a gigantic angler fish",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A gigantic angler fish throws itself at you, clamping its sickening jaw tight around your throat\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "blackout"],
    length: 2.0,
  },
  {
    user: "a gigantic angler fish",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A gigantic angler fish hurls itself at you in a vicious frontal attack, connecting painfully with your chest\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "stun"],
    length: 2.0,
  },
  {
    user: "a burly troll guard",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson: /^A burly troll guard batters you with an overhead blow\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 4.0,
  },
  {
    //TODO Identical pattern
    user: "a burly troll guard",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A burly troll guard screams with rage and drives his spear deep into your chest\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 4.0,
  },
  {
    //TODO Identical pattern
    user: "a burly troll guard",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A look of absolute rage takes over a burly troll guard as he lunges at you, sinking his abnormally sharp teeth deep into your throat\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 4.0,
  },
  {
    //TODO Identical pattern
    user: "a sturdy troll woman",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A sturdy troll woman screams with rage and drives her spear deep into your chest\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 4.0,
  },
  {
    //TODO Identical pattern
    user: "a sturdy troll woman",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A look of absolute rage takes over a sturdy troll woman as she lunges at you, sinking her abnormally sharp teeth deep into your throat\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 4.0,
  },
  {
    user: "a sturdy troll woman",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^A sturdy troll woman lowers her head and charges at you, slamming powerfully into your abdomen\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "stun"],
    length: 4.0,
  },
  {
    user: "Rinaga",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^His trusty shovel held firmly in both hands, Rinaga batters you powerfully around the head with it\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 3.0,
  },
  {
    user: "Rinaga",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^Rinaga swings a red-hot poker at you with considerable force, slamming it powerfully into the side of your head\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage"],
    length: 3.0,
  },
  {
    user: "Rinaga",
    areaId: [260],
    areaName: "the Caverns of Riagath",
    firstPerson:
      /^Using his shovel with outstanding accuracy, Rinaga scoops a pile of burning coals from his fire and launches them at you\.$/,
    secondPerson: false,
    thirdPerson: false,
    tags: ["damage", "burning"],
    length: 3.0,
  },
];
